### ISSUE TITLE
How to keep API token secret on React Native apps?

### ISSUE THREAD

**Issue by hyperh** [DripEmail/drip-nodejs#15]
So I'm looking into using `drip-nodejs` on React Native.

Normally for an analytics provider (e.g. Google Analytics) all I need is the app id, which is a public id.

However, `drip-nodejs` needs 

```
const client = require('drip-nodejs')(
  {
    token: YOUR_API_KEY,
    accountId: YOUR_ACCOUNT_ID
  }
);
```

And API token is supposed to be kept private. I'm assuming `drip-nodejs` is only supposed to be used on the server-side. So not sure how I would be sending events from the mobile app. Is there a similar interface on React Native like the Drip script on web that only requires the public app id?

**Comment by samudary** [comment]
@hyperh While I'm not a React Native expert, I don't see any issues with using this. I'd suggest using some kind of keychain interface to store sensitive data. For example, one of these: https://github.com/search?utf8=%E2%9C%93&q=react-native+keychain
