### ISSUE TITLE
Support for new Shopper Activity API

### ISSUE THREAD

**Issue by kblestarge** [DripEmail/drip-nodejs#19]
This is a feature request. Drip recently released a new API for tracking carts and other shopper activity. It would be nice to have that supported in this project.
https://developer.drip.com/#shopper_activity_overview
Is anyone already working on this? Or should I fork and submit a pull request?

**Comment by samudary** [comment]
Hi @kblestarge thanks for checking in and your willingness to contribute!

I have been monitoring progress of the shopper activity feature and intentionally delayed adding it to our package. Based on the conversation [here](https://github.com/DripEmail/drip-ruby/issues/55) it appears the Drip team still has a few features to flesh out that could potentially impact the final product. With that said, I have been weighing starting development but haven't prioritized. If adding this feature provides immediate value for you I'm open to you forking and submitting a pull request.

**Comment by kblestarge** [comment]
Pull request: https://github.com/samudary/drip-nodejs/pull/20

**Comment by samudary** [comment]
Thanks @kblestarge I'll take a look at this tomorrow.

**Comment by Cinamonas** [comment]
@samudary, I think the API stabilized by now, any chance to review and possibly merge @kblestarge’s PR?

**Comment by arincon9** [comment]
@samudary Hey, any chance we can get the pull request looked at? Would love to use the new Cart Activity functionality.

**Comment by samudary** [comment]
Thanks for the follow up @arincon9. The shopper activity updates are definitely way past due here. I'm gearing up to get these updates done in the coming week and bringing the package on par with the Drip API functionality.

**Comment by arincon9** [comment]
@samudary Thank you 🙏 ! You are very appreciated.

**Comment by samudary** [comment]
https://github.com/samudary/drip-nodejs/pull/23 in progress to address this. It ended up being a larger update than expected and now doing some final testing. Should be ready in a day or 2.

**Comment by samudary** [comment]
New version with shopper activity support has been published

**Comment by arincon9** [comment]
Thank you so much! @samudary
