### ISSUE TITLE
Documentation incorrect for createUpdateSubscriber

### ISSUE THREAD

**Issue by prkirby** [DripEmail/drip-nodejs#30]
Hello, 

Just had to spend about an hour debugging this, which was frustrating so hopefully this can be resolved or someone else having the same issue can find this in the future. 

The documentation at https://developer.drip.com/?javascript#create-or-update-a-subscriber states the payload for createUpdateUser should look like this: 

```
const payload = {
  subscribers: [{
    email: "john@acme.com",
    time_zone: "America/Los_Angeles",
    custom_fields: {
      shirt_size: "Medium"
    }
  }]
};
```

However, I was continuously getting this, very unhelpful error: 
`{"errors":[{"code":"parsing_error","message":"JSON parsing error: The property '#/' of type object did not match one or more of the required schemas"}]}`

After triple checking all of my custom field identifiers and racking my brain, I logged the actual entire error response and noticed the body of the request was this: 
`body: '{"subscribers":[{"subscribers":[{"email":"test90@quiz.com"}]}]}',`

So while the documentation is telling you to have your subscriber wrapped in an array under subscribers, you are actually just supposed to send only the subscriber object, like this: 

```
const payload = {
    email: "john@acme.com",
    time_zone: "America/Los_Angeles",
    custom_fields: {
      shirt_size: "Medium"
    }
};
```

Hopefully you guys can make that small change in the documentation, and maybe this issue will help others before that happens. Thanks!

**Comment by trybases** [comment]
Thanks a lot!

**Comment by davetann** [comment]
Thanks for this

**Comment by h01m3s** [comment]
Thank you! I was working on this and keep getting the same error.

**Comment by g-hamilton** [comment]
Thanks! I was pulling my hair out for an hour.

**Comment by sloreti** [comment]
Ah, thank you @prkirby! Authored a PR to fix it in the Drip docs here, [https://github.com/DripEmail/api-docs/pull/91](https://github.com/DripEmail/api-docs/pull/91).

**Comment by Valchy** [comment]
Jesus Christ, why did I see this so late. Thank you so much!

**Comment by sloreti** [comment]
@jeremyhaberman Is it possible to get https://github.com/DripEmail/api-docs/pull/91 merged? This seems to be a common pitfall. (Apologies if you're the wrong person to tag, but you're the most recent maintainer I see)

**Comment by jeremyhaberman** [comment]
@sloreti, I'm not sure. I'm probably not the best one to ask. No worries about reaching out to me though.

@will-in-wi, can you help out with this?

**Comment by will-in-wi** [comment]
https://github.com/DripEmail/api-docs/pull/91 is merged, and this should be fixed now.
