### ISSUE TITLE
Failed to `Subscribe someone to a campaign` and `Create or update a batch of subscribers`

### ISSUE THREAD

**Issue by ostriandoni** [DripEmail/drip-nodejs#9]
Hello, please advise:

**1) Subscribe someone to a campaign**
- endpoint:
 https://api.getdrip.com/v2/MY_ACC_ID/campaigns/MY_CAMPAIGN_ID/subscribers

- payload: (I copy paste from documentation http://developer.drip.com/#subscribe-someone-to-a-campaign with some changes value of variable)
```
{
  "email": "someone@example.com",
  "time_zone": "Asia/Kuala_Lumpur",
  "custom_fields": {
    "name": "Jane Doe"
  }
}
```
- response:
```
{
    "errors": [
        {
            "code": "parsing_error",
            "message": "JSON parsing error: The property '#/' of type Hash did not match one or more of the required schemas"
        }
    ]
}
```

**2) Create or update a batch of subscribers**
- endpoint:
 https://api.getdrip.com/v2/MY_ACC_ID/subscribers/batches

- payload: (I copy paste from documentation http://developer.drip.com/#create-or-update-a-batch-of-subscribers with some changes value of variable)
```
"batches": [{
    "subscribers": [
      {
        "email": "john@acme.com",
        "tags": "early-access"
      },
      {
        "email": "jane@acme.com",
        "tags": "early-access"
      }
    ]
  }]
```
- response:
```
{
    "status": 400,
    "error": "There was a problem in the JSON you submitted: 822: unexpected token at ': [{\n    \"subscribers\": [\n      {\n        \"email\": \"john@acme.com\",\n        \"tags\": \"early-access\"\n      },\n      {\n        \"email\": \"jane@acme.com\",\n        \"tags\": \"early-access\"\n      }\n    ]\n  }]'"
}
```

**Comment by samudary** [comment]
@ostriandoni I'm looking into this. In the meantime, could you post the actual code you used when you got these errors? Thanks

**Comment by ostriandoni** [comment]
@samudary please find below:

**1) Subscribe someone to a campaign** (will get error like mentioned above)
```
  async assignToCampaign(ctx) {
    const payload = {
      "email": "someone@example.com",
      "time_zone": "Asia/Kuala_Lumpur",
      "custom_fields": {
        "name": "Jane Doe"
      }
    }

    campaign = await client.subscribeToCampaign(MY_CAMPAIGN_ID, payload)

    ctx.body = {
      campaign
    }
  }
```

**2) Create or update a batch of subscribers** (I got different error: `errors [ Error: Invalid URI "MY_ACCOUNT_ID/subscribers/batches"`)
```
  async bulkUploadExistingEmails(ctx) {
    const payload = {
      "batches": [{
        "subscribers": [
          {
            "email": "john@acme.com",
            "tags": "early-access"
          },
          {
            "email": "jane@acme.com",
            "tags": "early-access"
          }
        ]
      }]
    }

    const subscribers = client.updateBatchSubscribers(payload, (errors, responses, bodies) => {
      console.log('errors', errors)
      console.log('responses', errors)
      console.log('bodies', bodies)
    })

    ctx.body = {
      subscribers
    }
  }
```

**Comment by samudary** [comment]
For the [campaign subscribers endpoint](http://developer.drip.com/#subscribe-someone-to-a-campaign), the Drip API requires the payload to be in this format:

```
{
  subscribers: [{
    email: "someone@example.com",
    time_zone: "Asia/Kuala_Lumpur",
    custom_fields: {
      name: "Jane Doe"
    }
  }]
}
```

The subscriber data needs to be within an array: `subscribers: [ ... ]`

For the subscribers batch method, I've found the issue and can get a fix out shortly.

**Comment by ostriandoni** [comment]
@samudary oh I see. It is work now for the campaign subscribers endpoint.
I believe we should update example of documentation, so will not cause any confusion in the future.
Currently [on example](http://developer.drip.com/#subscribe-someone-to-a-campaign) it is said same as above:
```
const payload = {
  email: "someone@example.com",
  time_zone: "America/Los_Angeles",
  custom_fields: {
    name: "Jane Doe"
  }
}
```

For the subscribers batch method, I believe the new patch should fix it. Thank you.

**Comment by samudary** [comment]
Will confirm once the new version is published to NPM

**Comment by samudary** [comment]
Updates published.

**Comment by ostriandoni** [comment]
Thank you very much.

**Comment by alejandrom2** [comment]
I am having a very similar issue to this after using the following payload
```
const payload = {
    subscribers: [
      {
        email: 'email@gmail.com',
      },
    ],
  };
return client
    .subscribeToCampaign(#########, payload)
.then((resp) => console.log({resp}))
    .catch((error) => {
      console.log({error});
    });
...
```
I am receiving the following error in my catch: 
>message:"JSON parsing error: The property '#/' of type object did not match one or more of the required schemas"

**Comment by kelleymuro** [comment]
I am getting the same issue above. Is there a fix for this?

https://imgur.com/a/kgvFCML

**Comment by carllippert** [comment]
@kelleymuro pass as object rather than Array. Just solved myself. Generated docs will send you astray.

**Comment by swordfish2011** [comment]
I also have the same problem with a PHP script.

I don't know what I am doing wrong.

Here is some sample from my code

<pre>$this->data = array(
	'subscribers' => array(
		'email' => $this->email,
		'first_name' => $this->firstName,
		'last_name'  => $this->lastName,
	),
);

protected function data(){
	return json_encode( $this->data );
}</pre>

Can someone help me please?

**Comment by swordfish2011** [comment]
Nevermind I solved it.

It seems that I was missing an array. The email, name, last name etc... should be wrapped in another array. 

The working code if someone else has this issue:

<pre>
			$this->data = array(
				'subscribers' => array(
					array( 
						'email' 	 => $this->email,
						'first_name' => $this->firstName,
						'last_name'  => $this->lastName 
					),
				),
			);
</pre>

**Comment by mohsinraza** [comment]
**I am adding a new subscriber in drip with the below code. You can follow it.**

```
$ch = curl_init();

//YOUR-ACCOUNT-ID replace it with your account id
curl_setopt($ch, CURLOPT_URL, 'https://api.getdrip.com/v2/YOUR-ACCOUNT-ID/subscribers');

curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
$data = array(
                'subscribers' => array(
                    array( 
                        'email'      => 'myemail@domain.com',
                        'first_name' => 'Mohsin',
                        'last_name'  => 'raza' 
                    ),
                ),
            );
$post = json_encode($data);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);

//YOUR-API-TOKEN-HERE replace it with your api-token
curl_setopt($ch, CURLOPT_USERPWD, 'YOUR-API-TOKEN-HERE' . ':' . '');

$headers = array();

//replace with your app name and registered domain with drip account
$headers[] = 'User-Agent: YOUR-APP-NAME (www.your-domain.com)';

$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
echo $result; 
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
```

**Comment by rishabh-rastogi215** [comment]
```
      const data = {
        email: document.email,
        first_name: document.firstName,
        last_name: document.lastName
      }

      const response = await client.createUpdateSubscriber(data)
```


This is what works as of 9/2/21
